POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "xkcd",
    "author": "Randall Munroe",
    "url": "https://what-if.xkcd.com/",
    "likes": 13,
    "userId": "60303d033983fa69c7e9aa4b"
}